x-kiosk: Update Application
foundriesio/containers pull request #15
Opened 2021-11-08 18:52 UTC by munoz0raul

- Changed based image to debian:bullseye-slim
- Updated the USER id to weston (63).

2021-11-08 20:33 UTC, mike-scott commented on x-kiosk/Dockerfile
> +# docker run -it --rm -v /tmp/.X11-unix:/tmp/.X11-unix -v /var/run/dbus:/var/dbus hub.foundries.io/lmp/x-kiosk:latest www.foundries.io
Let's fix this line to:
```
# docker run -it --rm -v /tmp/.X11-unix:/tmp/.X11-unix --user "63" hub.foundries.io/lmp/x-kiosk:latest www.foundries.io
```

2021-11-08 20:34 UTC, mike-scott requested changes
Looks good except for the testing commands.  Can you verify my change still works?

2021-11-08 20:34 UTC, mike-scott commented
And we should squash the 2 commits into 1.

2021-11-08 20:51 UTC, munoz0raul commented on x-kiosk/Dockerfile
> +# docker run -it --rm -v /tmp/.X11-unix:/tmp/.X11-unix -v /var/run/dbus:/var/dbus hub.foundries.io/lmp/x-kiosk:latest www.foundries.io
done!

2021-11-08 20:53 UTC, munoz0raul commented
@mike-scott, I updated the command to what I have used and squashed the commits. Builds are falling, didn't see if was working before. Do you know if these actions are up-to-date?

2021-11-08 20:55 UTC, mike-scott approved these changes
LGTM

2021-11-30 01:25 UTC, mike-scott commented
ci test

2021-11-30 01:26 UTC, merged